
namespace Buckle.CodeAnalysis.Binding;

/// <summary>
/// Types of bound nodes.
/// </summary>
internal enum BoundKind : byte {
    ConditionalExpression,
    BinaryExpression,
    UnaryExpression,
    LiteralExpression,
    DataContainerExpression,
    AssignmentExpression,
    EmptyExpression,
    CallExpression,
    ArrayAccessExpression,
    CastExpression,
    CompoundAssignmentExpression,
    ReferenceExpression,
    TypeOfExpression,
    ObjectCreationExpression,
    ArrayCreationExpression,
    FieldAccessExpression,
    ConditionalAccessExpression,
    ThisExpression,
    BaseExpression,
    ExtendExpression,
    ThrowExpression,
    InitializerListExpression,
    InitializerDictionaryExpression,
    TypeExpression,
    ParameterExpression,
    IsExpression,
    IsntExpression,
    AsExpression,
    NullCoalescingExpression,
    NullAssertExpression,
    ValuePlaceholder,

    BlockStatement,
    ExpressionStatement,
    LocalDeclarationStatement,
    IfStatement,
    WhileStatement,
    ForStatement,
    GotoStatement,
    LabelStatement,
    ConditionalGotoStatement,
    DoWhileStatement,
    TryStatement,
    ReturnStatement,
    BreakStatement,
    ContinueStatement,

    DataContainerDeclaration,
    FieldEqualsValue,
    ParameterEqualsValue,
    TemplateParameterEqualsValue,
    GlobalStatement,
    MethodGroup,
    ConstructorMethodBody,
    NonConstructorMethodBody,
}
