using Buckle.CodeAnalysis.Symbols;

namespace Buckle.CodeAnalysis.Binding;

/// <summary>
/// Generated by the <see cref="Lowering.Lowerer" />.
/// E.g.
/// <code>
/// goto label if condition
/// </code>
/// </summary>
internal sealed class BoundConditionalGotoStatement : BoundStatement {
    internal BoundConditionalGotoStatement(LabelSymbol label, BoundExpression condition, bool jumpIfTrue = true) {
        this.label = label;
        this.condition = condition;
        this.jumpIfTrue = jumpIfTrue;
    }

    internal override BoundNodeKind kind => BoundNodeKind.ConditionalGotoStatement;

    internal LabelSymbol label { get; }

    internal BoundExpression condition { get; }

    internal bool jumpIfTrue { get; }
}
