using Buckle.CodeAnalysis.Symbols;

namespace Buckle.CodeAnalysis.Binding;

/// <summary>
/// Generated by the <see cref="Lowering.Lowerer" />.
/// <br/>
/// E.g.
/// <code>
/// goto label
/// </code>
/// </summary>
internal sealed class BoundGotoStatement : BoundStatement {
    internal BoundGotoStatement(LabelSymbol label) {
        this.label = label;
    }

    internal override BoundNodeKind kind => BoundNodeKind.GotoStatement;

    internal LabelSymbol label { get; }
}
