using Buckle.CodeAnalysis.Symbols;

namespace Buckle.CodeAnalysis.Binding;

/// <summary>
/// Generated by the <see cref="Lowering.Lowerer" />.
/// <br/>
/// E.g.
/// <code>
/// label1:
/// </code>
/// </summary>
internal sealed class BoundLabelStatement : BoundStatement {
    internal BoundLabelStatement(LabelSymbol label) {
        this.label = label;
    }

    internal override BoundNodeKind kind => BoundNodeKind.LabelStatement;

    internal LabelSymbol label { get; }
}
