
namespace Buckle.CodeAnalysis.Binding;

/// <summary>
/// Generated by the compiler, not present in the final tree.
/// </summary>
internal sealed class BoundNonConstructorMethodBody : BoundMethodBodyBase {
    internal BoundNonConstructorMethodBody(BoundBlockStatement body) : base(body) { }

    internal override BoundNodeKind kind => BoundNodeKind.NonConstructorMethodBody;
}
