using Buckle.CodeAnalysis.Syntax;

namespace Buckle.CodeAnalysis.Binding;

/// <summary>
/// Generated by the compiler, not present in the final tree.
/// </summary>
internal sealed class BoundNonConstructorMethodBody : BoundMethodBodyBase {
    internal BoundNonConstructorMethodBody(SyntaxNode syntax, BoundBlockStatement body, bool hasErrors = false)
        : base(BoundKind.NonConstructorMethodBody, syntax, body, hasErrors) { }
}
