using Buckle.CodeAnalysis.Symbols;
using Buckle.CodeAnalysis.Syntax;

namespace Buckle.CodeAnalysis.Binding;

/// <summary>
/// Generated by the <see cref="Lowering.Lowerer" />.
/// </summary>
internal sealed class BoundLabelStatement : BoundStatement {
    internal BoundLabelStatement(SyntaxNode syntax, LabelSymbol label, bool hasErrors = false)
        : base(BoundKind.LabelStatement, syntax, hasErrors) {
        this.label = label;
    }

    internal LabelSymbol label { get; }
}
