using System.Collections.Immutable;
using Buckle.CodeAnalysis.Symbols;

namespace Buckle.CodeAnalysis.Binding;

/// <summary>
/// Generated by the compiler, not present in the final tree.
/// </summary>
internal sealed class BoundMethodGroup : BoundExpression {
    internal BoundMethodGroup(
        string name,
        ImmutableArray<MethodSymbol> methods,
        ImmutableArray<TypeOrConstant> templateArguments) {
        this.name = name;
        this.methods = methods;
        this.templateArguments = templateArguments;
    }

    internal override BoundNodeKind kind => BoundNodeKind.MethodGroup;

    internal override TypeSymbol type => null;

    internal string name { get; }

    internal ImmutableArray<MethodSymbol> methods { get; }

    internal ImmutableArray<TypeOrConstant> templateArguments { get; }
}
