
name: UnitTests

on:
  push:
  workflow_dispatch:

jobs:
  Test:
    runs-on: windows-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v3
        with:
          global-json-file: global.json

      - name: Clean
        run: dotnet clean --configuration Release ./src/Buckle/Buckle.sln

      - name: Generate
        run: make generate

      - name: Build
        run: dotnet build -t:rebuild --configuration Release ./src/Buckle/Buckle.sln

      - name: Test
        run: dotnet test --configuration Release ./src/Buckle/Buckle.sln
