
name: UnitTests

on:
  push:
  workflow_dispatch:

jobs:
  Test:
    runs-on: windows-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v3
        with:
          global-json-file: global.json

      - name: Clean
        run: make clean

      - name: Generate
        run: make generate

      - name: Build
        run: make

      - name: Test
        run: make test
