
name: UnitTests

on:
  push:
  workflow_dispatch:

jobs:
  Test:
    runs-on: windows-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Clean
        run: dotnet clean --configuration Release ./src/Buckle/Buckle.sln

      - name: Build
        run: dotnet build ./src/Buckle/Buckle.sln -t:rebuild |
             dotnet build ./src/Buckle/Buckle.sln -t:rebuild --configuration Release

      - name: Test
        run: dotnet test --configuration Release ./src/Buckle/Buckle.Tests/Buckle.Tests.csproj
