
name: UnitTests

on:
  push:
    branches:
      - main
      - staging
  workflow_dispatch:

jobs:
  Test:
    runs-on: windows-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Build
        run: dotnet build --configuration Release ./src/Buckle/Buckle.Tests/Buckle.Tests.csproj

      - name: Test
        run: dotnet test --configuration Release ./src/Buckle/Buckle.Tests/Buckle.Tests.csproj
